; Interrupt Descriptor Table for DevOS
; IDT is initialized in kernel/idt.c with:
;   - 256 entries (vectors 0-255)
;   - Each entry stores: offset (64-bit handler), code segment selector,
;     IST index, gate type (interrupt/trap), DPL
;   - Vector stubs generated by arch/genvectors.py -> arch/vectors.S
;   - Each stub pushes vector number, then jumps to common handler
;   - Common handler calls C handler functions
;
; IDT loaded at runtime via lidt instruction in kernel/idt.c:idt_enable().
;
; See kernel/idt.c, arch/vectors.S, and arch/genvectors.py.
