#include "wine_stubs.h"
#include "kprintf.h"
#include "string.h"

/* ── Stub generators ── */
static uint64_t stub_success(void)  { return 0; }
static uint64_t stub_fail(void)     { return 0xC000000D; }
static uint64_t stub_alert(void)    { return 0x102; }
static uint64_t stub_one(void)      { return 1; }
static uint64_t stub_zero(void)     { return 0; }
static uint64_t stub_invalid(void)  { return (uint64_t)(int64_t)-1; }
static uint64_t stub_handle(void)   { return 0; }
static uint64_t stub_noop(void)     { return 0; }
static uint64_t stub_260(void)      { return 260; }
static uint64_t stub_65001(void)    { return 65001; }
static uint64_t stub_437(void)      { return 437; }
static uint64_t stub_win10(void)    { return 0x80000005; }
static uint64_t stub_curthread(void) { return (uint64_t)(int64_t)-2; }
static uint64_t stub_curproc(void)  { return (uint64_t)(int64_t)-1; }

/* ── Stub table ── */
/* Using a simple flat array. Lookup iterates. */
static const win32_stub_entry_t stubs[] = {
    /* ntdll.dll */
    {"ntdll.dll", "NtClose",                          0, stub_success},
    {"ntdll.dll", "NtCreateFile",                     0, stub_fail},
    {"ntdll.dll", "NtReadFile",                       0, stub_fail},
    {"ntdll.dll", "NtWriteFile",                      0, stub_fail},
    {"ntdll.dll", "NtAllocateVirtualMemory",          0, stub_fail},
    {"ntdll.dll", "NtFreeVirtualMemory",              0, stub_fail},
    {"ntdll.dll", "NtQueryVirtualMemory",             0, stub_fail},
    {"ntdll.dll", "NtProtectVirtualMemory",           0, stub_fail},
    {"ntdll.dll", "NtQuerySystemInformation",         0, stub_fail},
    {"ntdll.dll", "NtQueryInformationProcess",        0, stub_fail},
    {"ntdll.dll", "NtSetInformationProcess",          0, stub_fail},
    {"ntdll.dll", "NtCreateSection",                  0, stub_fail},
    {"ntdll.dll", "NtMapViewOfSection",               0, stub_fail},
    {"ntdll.dll", "NtUnmapViewOfSection",             0, stub_fail},
    {"ntdll.dll", "NtCreateThread",                   0, stub_fail},
    {"ntdll.dll", "NtResumeThread",                   0, stub_fail},
    {"ntdll.dll", "NtQueryInformationThread",         0, stub_fail},
    {"ntdll.dll", "NtSetInformationThread",           0, stub_fail},
    {"ntdll.dll", "NtWaitForSingleObject",            0, stub_fail},
    {"ntdll.dll", "NtWaitForMultipleObjects",         0, stub_fail},
    {"ntdll.dll", "NtCreateEvent",                    0, stub_fail},
    {"ntdll.dll", "NtSetEvent",                       0, stub_fail},
    {"ntdll.dll", "NtResetEvent",                     0, stub_fail},
    {"ntdll.dll", "NtCreateMutant",                   0, stub_fail},
    {"ntdll.dll", "NtReleaseMutant",                  0, stub_fail},
    {"ntdll.dll", "NtCreateSemaphore",                0, stub_fail},
    {"ntdll.dll", "NtReleaseSemaphore",               0, stub_fail},
    {"ntdll.dll", "NtCreateKey",                      0, stub_fail},
    {"ntdll.dll", "NtOpenKey",                        0, stub_fail},
    {"ntdll.dll", "NtQueryValueKey",                  0, stub_fail},
    {"ntdll.dll", "NtSetValueKey",                    0, stub_fail},
    {"ntdll.dll", "NtDeleteKey",                      0, stub_fail},
    {"ntdll.dll", "NtDelayExecution",                 0, stub_success},
    {"ntdll.dll", "NtTestAlert",                      0, stub_alert},
    {"ntdll.dll", "NtRaiseException",                 0, stub_fail},
    {"ntdll.dll", "NtContinue",                       0, stub_fail},
    {"ntdll.dll", "NtGetContextThread",               0, stub_fail},
    {"ntdll.dll", "NtSetContextThread",               0, stub_fail},
    {"ntdll.dll", "NtDuplicateObject",                0, stub_fail},
    {"ntdll.dll", "NtQueryObject",                    0, stub_fail},
    {"ntdll.dll", "NtOpenDirectoryObject",            0, stub_fail},
    {"ntdll.dll", "NtCreateDirectoryObject",          0, stub_fail},
    {"ntdll.dll", "NtQueryDirectoryFile",             0, stub_fail},
    {"ntdll.dll", "NtFsControlFile",                  0, stub_fail},
    {"ntdll.dll", "NtReadVirtualMemory",              0, stub_fail},
    {"ntdll.dll", "NtWriteVirtualMemory",             0, stub_fail},
    {"ntdll.dll", "NtLockFile",                       0, stub_fail},
    {"ntdll.dll", "NtUnlockFile",                     0, stub_fail},
    {"ntdll.dll", "NtFlushBuffersFile",               0, stub_success},
    {"ntdll.dll", "NtDeviceIoControlFile",            0, stub_fail},
    {"ntdll.dll", "NtOpenThread",                     0, stub_fail},
    {"ntdll.dll", "NtOpenProcess",                    0, stub_fail},
    {"ntdll.dll", "NtCreateUserProcess",              0, stub_fail},
    {"ntdll.dll", "NtTerminateProcess",               0, stub_success},
    {"ntdll.dll", "NtQueryFullAttributesFile",        0, stub_fail},
    {"ntdll.dll", "NtCreateSymbolicLinkObject",       0, stub_fail},
    {"ntdll.dll", "RtlInitUnicodeString",             0, stub_noop},
    {"ntdll.dll", "RtlInitAnsiString",                0, stub_noop},
    {"ntdll.dll", "RtlUnicodeStringToAnsiString",     0, stub_fail},
    {"ntdll.dll", "RtlAnsiStringToUnicodeString",     0, stub_fail},
    {"ntdll.dll", "RtlFreeUnicodeString",             0, stub_noop},
    {"ntdll.dll", "RtlFreeAnsiString",                0, stub_noop},
    {"ntdll.dll", "RtlGetVersion",                    0, stub_zero},

    /* kernel32.dll */
    {"kernel32.dll", "SetLastError",                  0, stub_noop},
    {"kernel32.dll", "GetLastError",                  0, stub_zero},
    {"kernel32.dll", "GetStdHandle",                  0, stub_zero},
    {"kernel32.dll", "CreateFileA",                   0, stub_invalid},
    {"kernel32.dll", "CreateFileW",                   0, stub_invalid},
    {"kernel32.dll", "ReadFile",                      0, stub_zero},
    {"kernel32.dll", "WriteFile",                     0, stub_zero},
    {"kernel32.dll", "CloseHandle",                   0, stub_one},
    {"kernel32.dll", "CreateProcessA",                0, stub_zero},
    {"kernel32.dll", "CreateProcessW",                0, stub_zero},
    {"kernel32.dll", "ExitProcess",                   0, stub_noop},
    {"kernel32.dll", "TerminateProcess",              0, stub_one},
    {"kernel32.dll", "VirtualAlloc",                  0, stub_zero},
    {"kernel32.dll", "VirtualFree",                   0, stub_one},
    {"kernel32.dll", "VirtualProtect",                0, stub_one},
    {"kernel32.dll", "VirtualQuery",                  0, stub_zero},
    {"kernel32.dll", "HeapCreate",                    0, stub_zero},
    {"kernel32.dll", "HeapAlloc",                     0, stub_zero},
    {"kernel32.dll", "HeapFree",                      0, stub_one},
    {"kernel32.dll", "GetModuleHandleA",              0, stub_zero},
    {"kernel32.dll", "GetModuleHandleW",              0, stub_zero},
    {"kernel32.dll", "GetModuleFileNameA",            0, stub_zero},
    {"kernel32.dll", "GetModuleFileNameW",            0, stub_zero},
    {"kernel32.dll", "LoadLibraryA",                  0, stub_zero},
    {"kernel32.dll", "LoadLibraryW",                  0, stub_zero},
    {"kernel32.dll", "LoadLibraryExA",                0, stub_zero},
    {"kernel32.dll", "LoadLibraryExW",                0, stub_zero},
    {"kernel32.dll", "FreeLibrary",                   0, stub_one},
    {"kernel32.dll", "GetProcAddress",                0, stub_zero},
    {"kernel32.dll", "GetSystemInfo",                 0, stub_zero},
    {"kernel32.dll", "GetNativeSystemInfo",           0, stub_zero},
    {"kernel32.dll", "GetCurrentThread",              0, stub_curthread},
    {"kernel32.dll", "GetCurrentProcess",             0, stub_curproc},
    {"kernel32.dll", "GetCurrentProcessId",           0, stub_one},
    {"kernel32.dll", "GetCurrentThreadId",            0, stub_one},
    {"kernel32.dll", "CreateThread",                  0, stub_zero},
    {"kernel32.dll", "CreateEventA",                  0, stub_zero},
    {"kernel32.dll", "CreateEventW",                  0, stub_zero},
    {"kernel32.dll", "CreateMutexA",                  0, stub_zero},
    {"kernel32.dll", "CreateMutexW",                  0, stub_zero},
    {"kernel32.dll", "CreateSemaphoreA",              0, stub_zero},
    {"kernel32.dll", "CreateSemaphoreW",              0, stub_zero},
    {"kernel32.dll", "WaitForSingleObject",           0, stub_alert},
    {"kernel32.dll", "WaitForMultipleObjects",        0, stub_alert},
    {"kernel32.dll", "SetEvent",                      0, stub_one},
    {"kernel32.dll", "ResetEvent",                    0, stub_one},
    {"kernel32.dll", "ReleaseMutex",                  0, stub_one},
    {"kernel32.dll", "ReleaseSemaphore",              0, stub_one},
    {"kernel32.dll", "Sleep",                         0, stub_noop},
    {"kernel32.dll", "SleepEx",                       0, stub_zero},
    {"kernel32.dll", "QueryPerformanceCounter",       0, stub_one},
    {"kernel32.dll", "QueryPerformanceFrequency",     0, stub_one},
    {"kernel32.dll", "GetTickCount",                  0, stub_zero},
    {"kernel32.dll", "GetTickCount64",                0, stub_zero},
    {"kernel32.dll", "LocalAlloc",                    0, stub_zero},
    {"kernel32.dll", "LocalFree",                     0, stub_zero},
    {"kernel32.dll", "GlobalAlloc",                   0, stub_zero},
    {"kernel32.dll", "GlobalFree",                    0, stub_zero},
    {"kernel32.dll", "MultiByteToWideChar",           0, stub_zero},
    {"kernel32.dll", "WideCharToMultiByte",           0, stub_zero},
    {"kernel32.dll", "GetVersionA",                   0, stub_win10},
    {"kernel32.dll", "GetVersionExA",                 0, stub_one},
    {"kernel32.dll", "GetVersionExW",                 0, stub_one},
    {"kernel32.dll", "GetTempPathA",                  0, stub_260},
    {"kernel32.dll", "GetTempPathW",                  0, stub_260},
    {"kernel32.dll", "GetWindowsDirectoryA",          0, stub_260},
    {"kernel32.dll", "GetWindowsDirectoryW",          0, stub_260},
    {"kernel32.dll", "GetSystemDirectoryA",           0, stub_260},
    {"kernel32.dll", "GetSystemDirectoryW",           0, stub_260},
    {"kernel32.dll", "CreateDirectoryA",              0, stub_one},
    {"kernel32.dll", "CreateDirectoryW",              0, stub_one},
    {"kernel32.dll", "RemoveDirectoryA",              0, stub_one},
    {"kernel32.dll", "RemoveDirectoryW",              0, stub_one},
    {"kernel32.dll", "DeleteFileA",                   0, stub_one},
    {"kernel32.dll", "DeleteFileW",                   0, stub_one},
    {"kernel32.dll", "MoveFileA",                     0, stub_one},
    {"kernel32.dll", "MoveFileW",                     0, stub_one},
    {"kernel32.dll", "CopyFileA",                     0, stub_one},
    {"kernel32.dll", "CopyFileW",                     0, stub_one},
    {"kernel32.dll", "FindFirstFileA",                0, stub_invalid},
    {"kernel32.dll", "FindFirstFileW",                0, stub_invalid},
    {"kernel32.dll", "FindNextFileA",                 0, stub_zero},
    {"kernel32.dll", "FindNextFileW",                 0, stub_zero},
    {"kernel32.dll", "FindClose",                     0, stub_one},
    {"kernel32.dll", "GetFileAttributesA",            0, stub_invalid},
    {"kernel32.dll", "GetFileAttributesW",            0, stub_invalid},
    {"kernel32.dll", "SetFileAttributesA",            0, stub_one},
    {"kernel32.dll", "SetFileAttributesW",            0, stub_one},
    {"kernel32.dll", "GetFileSize",                   0, stub_invalid},
    {"kernel32.dll", "GetFileSizeEx",                 0, stub_one},
    {"kernel32.dll", "SetFilePointer",                0, stub_invalid},
    {"kernel32.dll", "SetFilePointerEx",              0, stub_one},
    {"kernel32.dll", "CreatePipe",                    0, stub_zero},
    {"kernel32.dll", "CreateFileMappingA",            0, stub_zero},
    {"kernel32.dll", "CreateFileMappingW",            0, stub_zero},
    {"kernel32.dll", "MapViewOfFile",                 0, stub_zero},
    {"kernel32.dll", "UnmapViewOfFile",               0, stub_one},
    {"kernel32.dll", "GetCurrentDirectoryA",          0, stub_260},
    {"kernel32.dll", "GetCurrentDirectoryW",          0, stub_260},
    {"kernel32.dll", "SetCurrentDirectoryA",          0, stub_one},
    {"kernel32.dll", "SetCurrentDirectoryW",          0, stub_one},
    {"kernel32.dll", "GetFullPathNameA",              0, stub_zero},
    {"kernel32.dll", "GetFullPathNameW",              0, stub_zero},
    {"kernel32.dll", "GetCommandLineA",               0, stub_zero},
    {"kernel32.dll", "GetCommandLineW",               0, stub_zero},
    {"kernel32.dll", "GetStartupInfoA",               0, stub_noop},
    {"kernel32.dll", "GetStartupInfoW",               0, stub_noop},
    {"kernel32.dll", "InitializeCriticalSection",     0, stub_noop},
    {"kernel32.dll", "EnterCriticalSection",          0, stub_noop},
    {"kernel32.dll", "LeaveCriticalSection",          0, stub_noop},
    {"kernel32.dll", "DeleteCriticalSection",         0, stub_noop},
    {"kernel32.dll", "InitializeCriticalSectionAndSpinCount", 0, stub_one},
    {"kernel32.dll", "InterlockedCompareExchange",    0, stub_zero},
    {"kernel32.dll", "InterlockedExchange",           0, stub_zero},
    {"kernel32.dll", "InterlockedIncrement",          0, stub_one},
    {"kernel32.dll", "InterlockedDecrement",          0, stub_zero},
    {"kernel32.dll", "TlsAlloc",                      0, stub_zero},
    {"kernel32.dll", "TlsFree",                       0, stub_one},
    {"kernel32.dll", "TlsGetValue",                   0, stub_zero},
    {"kernel32.dll", "TlsSetValue",                   0, stub_one},
    {"kernel32.dll", "GetACP",                        0, stub_65001},
    {"kernel32.dll", "GetOEMCP",                      0, stub_437},
    {"kernel32.dll", "IsValidCodePage",               0, stub_one},
    {"kernel32.dll", "GetCPInfo",                     0, stub_one},
    {"kernel32.dll", "IsDebuggerPresent",             0, stub_zero},
    {"kernel32.dll", "OutputDebugStringA",            0, stub_noop},
    {"kernel32.dll", "OutputDebugStringW",            0, stub_noop},
    {"kernel32.dll", "RaiseException",                0, stub_noop},
    {"kernel32.dll", "UnhandledExceptionFilter",      0, stub_zero},
    {"kernel32.dll", "SetUnhandledExceptionFilter",   0, stub_zero},
    {"kernel32.dll", "GetProcessHeap",                0, stub_zero},
    {"kernel32.dll", "FormatMessageA",                0, stub_zero},
    {"kernel32.dll", "FormatMessageW",                0, stub_zero},
    {"kernel32.dll", "GetCurrentProcess",             0, stub_curproc},
    {"kernel32.dll", "FlushFileBuffers",              0, stub_one},
    {"kernel32.dll", "GetFileType",                   0, stub_zero},
    {"kernel32.dll", "GetEnvironmentStrings",         0, stub_zero},
    {"kernel32.dll", "FreeEnvironmentStringsA",       0, stub_one},
    {"kernel32.dll", "GetEnvironmentVariableA",       0, stub_zero},
    {"kernel32.dll", "GetEnvironmentVariableW",       0, stub_zero},
    {"kernel32.dll", "SetEnvironmentVariableA",       0, stub_one},
    {"kernel32.dll", "SetEnvironmentVariableW",       0, stub_one},
    {"kernel32.dll", "GetComputerNameA",              0, stub_one},
    {"kernel32.dll", "GetComputerNameW",              0, stub_one},
    {"kernel32.dll", "GetUserNameA",                  0, stub_one},
    {"kernel32.dll", "GetUserNameW",                  0, stub_one},
    {"kernel32.dll", "GetLongPathNameA",              0, stub_zero},
    {"kernel32.dll", "GetLongPathNameW",              0, stub_zero},
    {"kernel32.dll", "GetShortPathNameA",             0, stub_zero},
    {"kernel32.dll", "GetShortPathNameW",             0, stub_zero},
    {"kernel32.dll", "CreateNamedPipeA",              0, stub_invalid},
    {"kernel32.dll", "CreateNamedPipeW",              0, stub_invalid},
    {"kernel32.dll", "PeekNamedPipe",                 0, stub_zero},

    /* user32.dll */
    {"user32.dll", "RegisterClassA",                  0, stub_zero},
    {"user32.dll", "RegisterClassW",                  0, stub_zero},
    {"user32.dll", "RegisterClassExA",                0, stub_zero},
    {"user32.dll", "RegisterClassExW",                0, stub_zero},
    {"user32.dll", "CreateWindowExA",                 0, stub_zero},
    {"user32.dll", "CreateWindowExW",                 0, stub_zero},
    {"user32.dll", "DestroyWindow",                   0, stub_one},
    {"user32.dll", "ShowWindow",                      0, stub_one},
    {"user32.dll", "UpdateWindow",                    0, stub_one},
    {"user32.dll", "GetMessageA",                     0, stub_zero},
    {"user32.dll", "GetMessageW",                     0, stub_zero},
    {"user32.dll", "PeekMessageA",                    0, stub_zero},
    {"user32.dll", "PeekMessageW",                    0, stub_zero},
    {"user32.dll", "TranslateMessage",                0, stub_zero},
    {"user32.dll", "DispatchMessageA",                0, stub_zero},
    {"user32.dll", "DispatchMessageW",                0, stub_zero},
    {"user32.dll", "PostQuitMessage",                 0, stub_noop},
    {"user32.dll", "DefWindowProcA",                  0, stub_zero},
    {"user32.dll", "DefWindowProcW",                  0, stub_zero},
    {"user32.dll", "MessageBoxA",                     0, stub_one},
    {"user32.dll", "MessageBoxW",                     0, stub_one},
    {"user32.dll", "MessageBoxExA",                   0, stub_one},
    {"user32.dll", "MessageBoxExW",                   0, stub_one},
    {"user32.dll", "GetDC",                           0, stub_zero},
    {"user32.dll", "ReleaseDC",                       0, stub_one},
    {"user32.dll", "BeginPaint",                      0, stub_zero},
    {"user32.dll", "EndPaint",                        0, stub_one},
    {"user32.dll", "GetClientRect",                   0, stub_one},
    {"user32.dll", "GetWindowRect",                   0, stub_one},
    {"user32.dll", "MoveWindow",                      0, stub_one},
    {"user32.dll", "SetWindowPos",                    0, stub_one},
    {"user32.dll", "SetWindowTextA",                  0, stub_one},
    {"user32.dll", "SetWindowTextW",                  0, stub_one},
    {"user32.dll", "GetWindowTextA",                  0, stub_zero},
    {"user32.dll", "GetWindowTextW",                  0, stub_zero},
    {"user32.dll", "GetWindowTextLengthA",            0, stub_zero},
    {"user32.dll", "GetWindowTextLengthW",            0, stub_zero},
    {"user32.dll", "FindWindowA",                     0, stub_zero},
    {"user32.dll", "FindWindowW",                     0, stub_zero},
    {"user32.dll", "SetTimer",                        0, stub_one},
    {"user32.dll", "KillTimer",                       0, stub_one},
    {"user32.dll", "PostMessageA",                    0, stub_one},
    {"user32.dll", "PostMessageW",                    0, stub_one},
    {"user32.dll", "SendMessageA",                    0, stub_zero},
    {"user32.dll", "SendMessageW",                    0, stub_zero},
    {"user32.dll", "CreateMenu",                      0, stub_zero},
    {"user32.dll", "CreatePopupMenu",                 0, stub_zero},
    {"user32.dll", "AppendMenuA",                     0, stub_one},
    {"user32.dll", "AppendMenuW",                     0, stub_one},
    {"user32.dll", "TrackPopupMenu",                 0, stub_one},
    {"user32.dll", "LoadIconA",                       0, stub_zero},
    {"user32.dll", "LoadIconW",                       0, stub_zero},
    {"user32.dll", "LoadCursorA",                     0, stub_zero},
    {"user32.dll", "LoadCursorW",                     0, stub_zero},
    {"user32.dll", "LoadBitmapA",                     0, stub_zero},
    {"user32.dll", "LoadBitmapW",                     0, stub_zero},
    {"user32.dll", "LoadStringA",                     0, stub_zero},
    {"user32.dll", "LoadStringW",                     0, stub_zero},
    {"user32.dll", "GetSystemMetrics",                0, stub_zero},
    {"user32.dll", "SystemParametersInfoA",           0, stub_one},
    {"user32.dll", "SystemParametersInfoW",           0, stub_one},
    {"user32.dll", "SetCapture",                      0, stub_zero},
    {"user32.dll", "ReleaseCapture",                  0, stub_one},
    {"user32.dll", "SetFocus",                        0, stub_zero},
    {"user32.dll", "GetFocus",                        0, stub_zero},
    {"user32.dll", "SetForegroundWindow",             0, stub_one},
    {"user32.dll", "GetForegroundWindow",             0, stub_zero},
    {"user32.dll", "GetDesktopWindow",                0, stub_zero},
    {"user32.dll", "GetParent",                       0, stub_zero},
    {"user32.dll", "SetParent",                       0, stub_zero},
    {"user32.dll", "EnableWindow",                    0, stub_one},
    {"user32.dll", "IsWindowEnabled",                 0, stub_zero},
    {"user32.dll", "IsWindowVisible",                 0, stub_zero},
    {"user32.dll", "InvalidateRect",                  0, stub_one},
    {"user32.dll", "GetDlgCtrlID",                    0, stub_zero},
    {"user32.dll", "GetDlgItem",                      0, stub_zero},
    {"user32.dll", "DialogBoxParamA",                 0, stub_invalid},
    {"user32.dll", "DialogBoxParamW",                 0, stub_invalid},
    {"user32.dll", "EndDialog",                       0, stub_one},
    {"user32.dll", "FlashWindow",                     0, stub_zero},
    {"user32.dll", "OpenClipboard",                   0, stub_one},
    {"user32.dll", "CloseClipboard",                  0, stub_one},
    {"user32.dll", "GetClipboardData",                0, stub_zero},
    {"user32.dll", "SetClipboardData",                0, stub_zero},
    {"user32.dll", "RegisterWindowMessageA",          0, stub_zero},
    {"user32.dll", "RegisterWindowMessageW",          0, stub_zero},
    {"user32.dll", "wsprintfA",                       0, stub_zero},
    {"user32.dll", "wsprintfW",                       0, stub_zero},
    {"user32.dll", "CharLowerA",                      0, stub_zero},
    {"user32.dll", "CharLowerW",                      0, stub_zero},
    {"user32.dll", "CharUpperA",                      0, stub_zero},
    {"user32.dll", "CharUpperW",                      0, stub_zero},
    {"user32.dll", "GetKeyNameTextA",                 0, stub_zero},
    {"user32.dll", "GetKeyNameTextW",                 0, stub_zero},
    {"user32.dll", "MapVirtualKeyA",                  0, stub_zero},
    {"user32.dll", "MapVirtualKeyW",                  0, stub_zero},

    /* gdi32.dll */
    {"gdi32.dll", "CreateDC",                         0, stub_zero},
    {"gdi32.dll", "CreateCompatibleDC",               0, stub_zero},
    {"gdi32.dll", "DeleteDC",                         0, stub_one},
    {"gdi32.dll", "CreateBitmap",                     0, stub_zero},
    {"gdi32.dll", "CreateDIBSection",                 0, stub_zero},
    {"gdi32.dll", "CreateCompatibleBitmap",           0, stub_zero},
    {"gdi32.dll", "SelectObject",                     0, stub_zero},
    {"gdi32.dll", "DeleteObject",                     0, stub_one},
    {"gdi32.dll", "BitBlt",                           0, stub_one},
    {"gdi32.dll", "StretchBlt",                       0, stub_one},
    {"gdi32.dll", "PatBlt",                           0, stub_one},
    {"gdi32.dll", "Rectangle",                        0, stub_one},
    {"gdi32.dll", "Ellipse",                          0, stub_one},
    {"gdi32.dll", "LineTo",                           0, stub_one},
    {"gdi32.dll", "MoveToEx",                         0, stub_one},
    {"gdi32.dll", "Polyline",                         0, stub_one},
    {"gdi32.dll", "Polygon",                          0, stub_one},
    {"gdi32.dll", "TextOutA",                         0, stub_one},
    {"gdi32.dll", "TextOutW",                         0, stub_one},
    {"gdi32.dll", "ExtTextOutA",                      0, stub_one},
    {"gdi32.dll", "ExtTextOutW",                      0, stub_one},
    {"gdi32.dll", "GetTextExtentPoint32A",            0, stub_one},
    {"gdi32.dll", "GetTextExtentPoint32W",            0, stub_one},
    {"gdi32.dll", "SetTextColor",                     0, stub_zero},
    {"gdi32.dll", "SetBkColor",                       0, stub_zero},
    {"gdi32.dll", "SetBkMode",                        0, stub_zero},
    {"gdi32.dll", "SetBrushOrgEx",                    0, stub_one},
    {"gdi32.dll", "GetStockObject",                   0, stub_zero},
    {"gdi32.dll", "CreateSolidBrush",                 0, stub_zero},
    {"gdi32.dll", "CreatePen",                        0, stub_zero},
    {"gdi32.dll", "CreateFontIndirectA",              0, stub_zero},
    {"gdi32.dll", "CreateFontIndirectW",              0, stub_zero},
    {"gdi32.dll", "GetDeviceCaps",                    0, stub_zero},
    {"gdi32.dll", "GetBitmapBits",                    0, stub_zero},
    {"gdi32.dll", "SetBitmapBits",                    0, stub_zero},
    {"gdi32.dll", "SetDIBColorTable",                 0, stub_zero},
    {"gdi32.dll", "GetDIBColorTable",                 0, stub_zero},
    {"gdi32.dll", "SetPixel",                         0, stub_zero},
    {"gdi32.dll", "GetPixel",                         0, stub_zero},
    {"gdi32.dll", "GetClipBox",                       0, stub_one},
    {"gdi32.dll", "IntersectClipRect",                0, stub_one},
    {"gdi32.dll", "RestoreDC",                        0, stub_one},
    {"gdi32.dll", "SaveDC",                           0, stub_one},
    {"gdi32.dll", "GetDCOrgEx",                       0, stub_one},
    {"gdi32.dll", "GdiFlush",                         0, stub_one},

    /* winmm.dll */
    {"winmm.dll", "timeGetTime",                      0, stub_zero},
    {"winmm.dll", "timeBeginPeriod",                  0, stub_one},
    {"winmm.dll", "timeEndPeriod",                    0, stub_one},
    {"winmm.dll", "waveOutOpen",                      0, stub_invalid},
    {"winmm.dll", "waveOutClose",                     0, stub_one},
    {"winmm.dll", "waveOutWrite",                     0, stub_one},
    {"winmm.dll", "PlaySoundA",                       0, stub_one},
    {"winmm.dll", "PlaySoundW",                       0, stub_one},

    /* ole32.dll */
    {"ole32.dll", "CoInitialize",                     0, stub_zero},
    {"ole32.dll", "CoInitializeEx",                   0, stub_zero},
    {"ole32.dll", "CoUninitialize",                   0, stub_noop},
    {"ole32.dll", "CoCreateInstance",                 0, stub_fail},
    {"ole32.dll", "CoTaskMemAlloc",                   0, stub_zero},
    {"ole32.dll", "CoTaskMemFree",                    0, stub_noop},

    /* advapi32.dll */
    {"advapi32.dll", "RegOpenKeyExA",                 0, stub_fail},
    {"advapi32.dll", "RegOpenKeyExW",                 0, stub_fail},
    {"advapi32.dll", "RegCreateKeyExA",               0, stub_fail},
    {"advapi32.dll", "RegCreateKeyExW",               0, stub_fail},
    {"advapi32.dll", "RegQueryValueExA",              0, stub_fail},
    {"advapi32.dll", "RegQueryValueExW",              0, stub_fail},
    {"advapi32.dll", "RegSetValueExA",                0, stub_fail},
    {"advapi32.dll", "RegSetValueExW",                0, stub_fail},
    {"advapi32.dll", "RegCloseKey",                   0, stub_zero},
    {"advapi32.dll", "GetTokenInformation",           0, stub_zero},
    {"advapi32.dll", "OpenProcessToken",              0, stub_one},
};

#define NUM_STUBS (sizeof(stubs) / sizeof(stubs[0]))

static int strcasecmp_simple(const char *a, const char *b) {
    while (*a && *b) {
        char ca = *a >= 'A' && *a <= 'Z' ? *a + 32 : *a;
        char cb = *b >= 'A' && *b <= 'Z' ? *b + 32 : *b;
        if (ca != cb) return ca - cb;
        a++; b++;
    }
    return *a - *b;
}

uint64_t wine_resolve_import(const char *dll, const char *name) {
    for (unsigned i = 0; i < NUM_STUBS; i++) {
        if (strcasecmp_simple(stubs[i].dll, dll) == 0 &&
            strcmp(stubs[i].name, name) == 0) {
            return (uint64_t)(uintptr_t)stubs[i].fn;
        }
    }
    kprintf("wine: unresolved import %s!%s\n", dll, name);
    return 0;
}

uint64_t wine_resolve_import_ordinal(const char *dll, uint16_t ordinal) {
    for (unsigned i = 0; i < NUM_STUBS; i++) {
        if (strcasecmp_simple(stubs[i].dll, dll) == 0 &&
            stubs[i].ordinal == ordinal) {
            return (uint64_t)(uintptr_t)stubs[i].fn;
        }
    }
    kprintf("wine: unresolved import %s!#%d\n", dll, ordinal);
    return 0;
}
