#!/usr/bin/env python3
"""gen_syscall_table.py — Generate a C syscall dispatch table from syscall.h.

Reads the SYSCALL_ defines and generates a function-pointer dispatch table
that replaces the manual switch statement. Optional: generates the table
header, the dispatch function, and a registration macro.

Usage:
    python3 scripts/gen_syscall_table.py                  # print to stdout
    python3 scripts/gen_syscall_table.py -o table.c      # write to file
    python3 scripts/gen_syscall_table.py --header-only    # header file only

Output: C source with a syscall_table[] array and a dispatch wrapper.
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
KERNEL_DIR = os.path.dirname(SCRIPT_DIR)
SYSCALL_H = os.path.join(KERNEL_DIR, "kernel", "syscall.h")


def parse_syscalls(path):
    syscalls = {}
    try:
        with open(path, "r") as f:
            content = f.read()
    except (OSError, IOError):
        return syscalls

    pat = re.compile(r"#define\s+SYSCALL_(\w+)\s+(\d+)")
    for m in pat.finditer(content):
        name = m.group(1)
        num = int(m.group(2))
        syscalls[num] = name

    return syscalls


def generate_header(syscalls):
    max_num = max(syscalls.keys()) if syscalls else 0
    lines = []
    lines.append("/* AUTO-GENERATED by gen_syscall_table.py — DO NOT EDIT */")
    lines.append("#ifndef SYSCALL_TABLE_H")
    lines.append("#define SYSCALL_TABLE_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define SYSCALL_COUNT {max_num + 1}")
    lines.append("")
    lines.append("typedef int64_t (*syscall_fn_t)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);")
    lines.append("")
    lines.append("/* Function declarations for each syscall handler */")
    for num in sorted(syscalls.keys()):
        name = syscalls[num]
        lines.append(f"int64_t sys_{name.lower()}(uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5);")
    lines.append("")
    lines.append("/* Dispatch table — indexed by syscall number */")
    lines.append("static syscall_fn_t syscall_table[SYSCALL_COUNT] = {")
    for num in range(max_num + 1):
        if num in syscalls:
            name = syscalls[num]
            lines.append(f"    [{num}] = sys_{name.lower()},  /* {name} */")
        else:
            lines.append(f"    [{num}] = NULL,")
    lines.append("};")
    lines.append("")
    lines.append("/* Dispatch function */")
    lines.append("static inline int64_t dispatch_syscall(uint64_t n, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5) {")
    lines.append("    if (n >= SYSCALL_COUNT || !syscall_table[n]) return -1;")
    lines.append("    return syscall_table[n](a1, a2, a3, a4, a5);")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* SYSCALL_TABLE_H */")
    return "\n".join(lines)


def generate_stubs(syscalls):
    lines = []
    lines.append("/* AUTO-GENERATED by gen_syscall_table.py — syscall handler stubs */")
    lines.append("/* Copy these into syscall.c and implement the actual logic. */")
    lines.append("")
    for num in sorted(syscalls.keys()):
        name = syscalls[num]
        func = f"sys_{name.lower()}"
        lines.append(f"int64_t {func}(uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5) {{")
        lines.append(f"    /* TODO: implement {name} (#{num}) */")
        lines.append(f"    (void)a1; (void)a2; (void)a3; (void)a4; (void)a5;")
        lines.append(f"    return -1;")
        lines.append(f"}}")
        lines.append("")
    return "\n".join(lines)


def main():
    header_only = False
    output_file = None

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--header-only":
            header_only = True
            i += 1
        elif args[i] == "-o" and i + 1 < len(args):
            output_file = args[i + 1]
            i += 2
        elif args[i] == "--help" or args[i] == "-h":
            print(__doc__)
            sys.exit(0)
        else:
            i += 1

    syscalls = parse_syscalls(SYSCALL_H)
    if not syscalls:
        print(f"Error: could not parse syscalls from {SYSCALL_H}", file=sys.stderr)
        sys.exit(1)

    if header_only:
        output = generate_header(syscalls)
    else:
        output = generate_header(syscalls) + "\n\n" + generate_stubs(syscalls)

    if output_file:
        with open(output_file, "w") as f:
            f.write(output)
        print(f"Written to {output_file}")
    else:
        print(output)


if __name__ == "__main__":
    main()
