[workspace]
members = [".", "crates/breadx", "crates/gdk4_x11", "crates/x11_overlay", "crates/mlua"]
resolver = "2"

[package]
name = "hyperde_shell"
version = "0.2.0"
edition = "2021"

[dependencies]
breadx = { path = "crates/breadx" }
gdk4_x11 = { path = "crates/gdk4_x11" }
x11_overlay = { path = "crates/x11_overlay" }
mlua = { path = "crates/mlua" }

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
